#spring.application.name=Loans

spring:
  application:
    name: "loans"
    version: v1

#  Database Connection properties
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/eazybank_microservices}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name:  com.mysql.cj.jdbc.Driver

  #    setting JPA properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  config:
    import: "optional:configserver:http://localhost:8071/"

#  setting application port
server:
  port: 8099

# Enabling all the endpoints of Spring boot actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"

