#spring.application.name=Loans

spring:
  application:
    name: Loan MicroService
    version: v1

#  Database Connection properties
  datasource:
    url: jdbc:mysql://localhost:3306/${DATABASE_NAME:eazybank_microservices}
    username: root
    password: root
    driver-class-name:  com.mysql.cj.jdbc.Driver

  #    setting JPA properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#  setting application port
server:
  port: 8099

